version: '3.9'

services:
  
  server:
    
    build: 
    
      context: ./

      dockerfile: ./dockerfiles/server.dockerfile

    ports:
      
      - "3000:3000"

    volumes:
      
      - /app/node_modules
      
      - ./src:/app/src

  dev:
  
    build: 
    
      context: ./

      dockerfile: ./dockerfiles/dev.dockerfile

    
      
    volumes:
      
      - ./lib:/app/lib
      - ./test:/app/test
  
    tty: true
    
    stdin_open: true
    
  
  
  preview:
    
    build: 
    
      context: ./

      dockerfile: ./dockerfiles/server.dockerfile

    ports:
      
      - "3000:3000"

    volumes:
      
      - /app/node_modules


  npm:
    
    build: 
      
      context: ./
      
      dockerfile: ./dockerfiles/npm.dockerfile
  

    tty: true
    
    stdin_open: true
    
    volumes:
      
      - ./:/app

  
  
  astro:
    
    build: 
      
      context: ./
      
      dockerfile: ./dockerfiles/astro.dockerfile
  
    tty: true
    
    stdin_open: true
    
    volumes:
           
      - ./:/app

